spring:
  profiles:
    group: # Run - Edit Configurations - Active Profiles에서 설정
      dev: common, dev
      prod: common, prod
---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&serverTimezone=UTC&useUnicode=true # 변경해주세요
    username: root # username
    password: password # password
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  OAuth2:
    kakao:
      url: https://kauth.kakao.com/oauth/authorize
      client-id: 44a90896f3ee78d0e03712d6cd025cfd
      client-secret:  # client-secret
      callback-login-url: http://localhost:3000/login/kakao
      token-request-url: https://kauth.kakao.com/oauth/token
      user-info-request-url: https://kapi.kakao.com/v2/user/me
      scope: account_email

server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  secret-key: UwKYibQQgkW7g-*k.ap9kje-wxBHb9wdXoBT4vnt4P3sJWt-Nu  # JWT key. 수정해주세요

---
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    database-platform: com.example.demo.common.config.CustomMySQLDialect
    hibernate:
      ddl-auto: none
      # create, update, create-drop, none 등의 옵션이 있습니다.
      # create: 기존테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      # create-drop: create와 같으나 종료 시점에 테이블 DROP
      # none: 사용하지 않음
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # DDl 생성 시 데이터베이스 고유의 기능 사용여부
    generate-ddl: false
    # 실행되는 쿼리문 보여주기 여부
    show-sql: false
    properties:
      hibernate:
        format_sql: false

---
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    database-platform: com.example.demo.common.config.CustomMySQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS